"""History maps: every film's interactive map in one app (generated by tools/maps_hub.py)."""

import json
from pathlib import Path

import streamlit as st
from streamlit.components.v2 import component

HERE = Path(__file__).parent
FILMS = sorted((json.loads((d / "meta.json").read_text()) | {"dir": d.name}
                for d in (HERE / "films").iterdir() if (d / "meta.json").exists()), key=lambda f: f["start"])

st.set_page_config(page_title="History in Maps", page_icon="🧭", layout="wide")
viewer = component("history_viewer", css=(HERE / "viewer" / "viewer.css").read_text(),
                   js=(HERE / "viewer" / "viewer.js").read_text())


def header(title: str, sub: str):
    st.markdown('<div class="tile-band"></div>', unsafe_allow_html=True)
    st.markdown(f'<div class="title-block"><h1>{title}</h1><div class="subtitle">{sub}</div></div>',
                unsafe_allow_html=True)


def film_page(f: dict):
    def page():
        d = HERE / "films" / f["dir"]
        st.markdown((d / "page.css").read_text(), unsafe_allow_html=True)
        header(f["title"]["en"], f["app_subtitle"])
        links = [(lbl, f["links"].get(k)) for k, lbl in (("youtube", "▶ Watch the documentary"),
                                                          ("youtube_pt", "▶ Assista ao documentário"),
                                                          ("store", "Maps & prints")) if f["links"].get(k)]
        if links:
            for col, (lbl, url) in zip(st.columns(len(links) + 3)[:len(links)], links):
                col.link_button(lbl, url, width="stretch")
        viewer(key=f"viewer-{f['dir']}", data=json.loads((d / "data.json").read_text()))
        st.caption("Regions are today's states; dates are approximate. Press ▶ to play, drag the slider to browse.")
        if f.get("sources"):
            with st.expander("Sources"):
                st.markdown("\n".join(f"- {s}" for s in f["sources"]))
    return page


def home():
    if FILMS:
        st.markdown((HERE / "films" / FILMS[0]["dir"] / "page.css").read_text(), unsafe_allow_html=True)
    header("History in Maps", "Animated, year-by-year maps from our documentaries")
    for f in FILMS:
        with st.container(border=True):
            st.markdown(f"### {f['title']['en']}  \n*{f['subtitle']['en']}*")
            st.page_link(PAGES[f["dir"]], label="Open the interactive map →")


PAGES = {f["dir"]: st.Page(film_page(f), title=f["title"]["en"], url_path=f["dir"]) for f in FILMS}
st.navigation([st.Page(home, title="All maps", url_path="home", default=True), *PAGES.values()],
              position="top").run()
